import Head from "next/head";
import Dashboard from "@/components/dashboard";
import { NextSeo } from "next-seo";
import { requireValidUser } from "@/utilities/authServer";

export default function Home({ pageData }) {
  return (
    <div>
      <Head>
        <title>My Dashboard</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <Dashboard pageData={pageData} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const { user, redirect } = await requireValidUser(context);
  if (redirect) return { redirect };

  const pageData = {};
  pageData.user = user;

  return { props: { pageData } };
}
